### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by wanghaisheng** [chou3ib1/slideshare-download-disabled-pdf#1]
python slideshare.py -u  http://www.slideshare.net/aiurchenko/iforum-iurchenkoux-eng  f 111.pdf                  

   ___ _                 _____ _ _     _ 
  / __\ |__   ___  _   _|___ /(_) |__ / |
 / /  | '_ \ / _ \| | | | |_ \| | '_ \| |
/ /___| | | | (_) | |_| |___) | | |_) | |
\____/|_| |_|\___/ \__,_|____/|_|_.__/|_|

parsing http://www.slideshare.net/aiurchenko/iforum-iurchenkoux-eng
44 slides found
Begin download slides : Please wait ...
End Download
Begin convert slides to pdf file
Traceback (most recent call last):
  File "slideshare.py", line 103, in <module>
    run()
  File "slideshare.py", line 65, in run
    merger.write(filename)
  File "/usr/local/lib/python2.7/site-packages/PyPDF2/merger.py", line 209, in write
    fileobj = file(fileobj, 'wb')
IOError: [Errno 2] No such file or directory: ''

**Comment by wanghaisheng** [comment]
miss -f  argument

**Comment by chou3ib1** [comment]
you missing "-" before "f"  :  - f 111.pdf
python slideshare.py -u http://www.slideshare.net/aiurchenko/iforum-iurchenkoux-eng -f 111.pdf

**Comment by chou3ib1** [comment]
this script missing the  testing  for  miss argu
