### ISSUE TITLE
could not run 

### ISSUE THREAD

**Issue by wanghaisheng** [chou3ib1/slideshare-download-disabled-pdf#2]
edwin@edwindeMacBook-Pro.local:/Users/edwin/Documents/workfolder/workspace/slideshare-download-disabled-pdf  git:(master) $ python slideshare.py -h
Traceback (most recent call last):
  File "slideshare.py", line 10, in <module>
    from include import parser, listoffiles
  File "/Users/edwin/Documents/workfolder/workspace/slideshare-download-disabled-pdf/include.py", line 4, in <module>
    from lxml import html
ImportError: No module named lxml

**Comment by wanghaisheng** [comment]
python 2.7.7
after clone repo,run the following commands:
pip install img2pdf
pip install PyPDF2
pip install requests
STATIC_DEPS=true sudo pip install lxml
but  lxml installation failed too

**Comment by chou3ib1** [comment]
i missed the lxml dependency  
so  use this commands to install it .
$ sudo apt-get update
$ sudo apt-get install libxml2-dev libxslt-dev
$ sudo pip install lxml

**Comment by wanghaisheng** [comment]
hi ,sorry for that. this is mac osx

**Comment by chou3ib1** [comment]
i found a soltion in stackoverflow website
open this link
http://stackoverflow.com/questions/1277124/how-do-you-install-lxml-on-os-x-leopard-without-using-macports-or-fink
